//
//  ClipboardMonitor.swift
//  clipplic
//

import AppKit
import Foundation

public final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general
    private var ignoredChangeCounts = Set<Int>()

    public var onItemCopied: ((ClipboardItem) -> Void)?

    // Known sensitive / transient pasteboard types
    private static let sensitivePasteboardTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type")
    ]

    public init() {
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.3) {
        stop()
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func markNextChangeAsIgnored() {
        // Will ignore the change count immediately following our write
        ignoredChangeCounts.insert(pasteboard.changeCount + 1)
    }

    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }

        lastChangeCount = currentChangeCount

        if ignoredChangeCounts.contains(currentChangeCount) {
            ignoredChangeCounts.remove(currentChangeCount)
            return
        }

        // Privacy Check: Skip concealed or password manager data
        if let types = pasteboard.types {
            let containsSensitiveType = types.contains { pasteboardType in
                Self.sensitivePasteboardTypes.contains(pasteboardType)
            }
            if containsSensitiveType {
                return
            }
        }

        // Extract text
        guard let rawString = pasteboard.string(forType: .string) else {
            return
        }

        let trimmed = rawString.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return
        }

        let frontmost = NSWorkspace.shared.frontmostApplication
        let appName = frontmost?.localizedName
        let bundleID = frontmost?.bundleIdentifier

        let rtfData = pasteboard.data(forType: .rtf)
        let type = detectContentType(for: rawString)

        let item = ClipboardItem(
            id: UUID(),
            contentType: type,
            textContent: rawString,
            rtfData: rtfData,
            createdAt: Date(),
            isPinned: false,
            sourceAppName: appName,
            sourceAppBundleID: bundleID
        )

        onItemCopied?(item)
    }

    private func detectContentType(for string: String) -> ItemContentType {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        // URL Check
        if trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://") {
            if let url = URL(string: trimmed), url.host != nil {
                return .url
            }
        }

        // Code heuristic check
        let codeIndicators = [
            "func ", "def ", "class ", "struct ", "enum ", "import ", "const ", "let ", "var ",
            "return ", "public ", "private ", "interface ", "package ", "namespace ",
            "=>", "->", "/*", "*/", "//", "{\n", "}\n", "console.log", "print("
        ]
        var score = 0
        for indicator in codeIndicators where string.contains(indicator) {
            score += 1
        }
        if score >= 2 || (string.contains("{") && string.contains("}") && string.contains(";")) {
            return .code
        }

        return .text
    }
}
