//
//  ClipboardMonitor.swift
//  clipplic
//

import AppKit
import CryptoKit
import Foundation

public final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard = NSPasteboard.general
    private var ignoredChangeCounts = Set<Int>()

    public var onItemCopied: ((ClipboardItem, Data?) -> Void)?

    // Sensitive / Transient pasteboard types to ignore
    private static let sensitivePasteboardTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type")
    ]

    public init() {
        self.lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.3) {
        stop()
        lastChangeCount = pasteboard.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    public func markNextChangeAsIgnored() {
        ignoredChangeCounts.insert(pasteboard.changeCount + 1)
    }

    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }

        lastChangeCount = currentChangeCount

        if ignoredChangeCounts.contains(currentChangeCount) {
            ignoredChangeCounts.remove(currentChangeCount)
            return
        }

        // Privacy Check: Skip concealed or password manager data
        if let types = pasteboard.types {
            let containsSensitive = types.contains { pasteboardType in
                Self.sensitivePasteboardTypes.contains(pasteboardType)
            }
            if containsSensitive {
                return
            }
        }

        let frontmost = NSWorkspace.shared.frontmostApplication
        let appName = frontmost?.localizedName
        let bundleID = frontmost?.bundleIdentifier
        let itemId = UUID()

        // 1. Check for Copied Image Data (Screenshots, browser images, Photoshop)
        if let (pngData, size) = extractImageData() {
            let hashString = "img:" + SHA256.hash(data: pngData).compactMap { String(format: "%02x", $0) }.joined()
            let fileName = "\(itemId.uuidString).png"
            let item = ClipboardItem(
                id: itemId,
                contentType: .image,
                textContent: nil,
                imageFileName: fileName,
                imageWidth: Double(size.width),
                imageHeight: Double(size.height),
                imageByteSize: pngData.count,
                filePaths: nil,
                createdAt: Date(),
                isPinned: false,
                sourceAppName: appName,
                sourceAppBundleID: bundleID,
                contentHash: hashString
            )
            onItemCopied?(item, pngData)
            return
        }

        // 2. Check for Copied Files (Finder)
        if let filePaths = extractFilePaths(), !filePaths.isEmpty {
            // Check if it's a single image file copied from Finder
            if filePaths.count == 1, isImageFilePath(filePaths[0]) {
                let path = filePaths[0]
                if let fileData = try? Data(contentsOf: URL(fileURLWithPath: path)),
                   let image = NSImage(data: fileData) {
                    let hashString = "img:" + SHA256.hash(data: fileData).compactMap { String(format: "%02x", $0) }.joined()
                    let fileName = "\(itemId.uuidString).png"
                    let item = ClipboardItem(
                        id: itemId,
                        contentType: .image,
                        textContent: nil,
                        imageFileName: fileName,
                        imageWidth: Double(image.size.width),
                        imageHeight: Double(image.size.height),
                        imageByteSize: fileData.count,
                        filePaths: filePaths,
                        createdAt: Date(),
                        isPinned: false,
                        sourceAppName: appName ?? "Finder",
                        sourceAppBundleID: bundleID,
                        contentHash: hashString
                    )
                    onItemCopied?(item, fileData)
                    return
                }
            }

            let contentHash = "files:" + filePaths.sorted().joined(separator: "|")
            let item = ClipboardItem(
                id: itemId,
                contentType: .file,
                textContent: filePaths.joined(separator: "\n"),
                filePaths: filePaths,
                createdAt: Date(),
                isPinned: false,
                sourceAppName: appName ?? "Finder",
                sourceAppBundleID: bundleID,
                contentHash: contentHash
            )
            onItemCopied?(item, nil)
            return
        }

        // 3. Check for Plain Text / Code / URLs
        if let rawString = pasteboard.string(forType: .string) {
            let trimmed = rawString.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return }

            let rtfData = pasteboard.data(forType: .rtf)
            let type = detectContentType(for: rawString)
            let contentHash = "text:" + rawString

            let item = ClipboardItem(
                id: itemId,
                contentType: type,
                textContent: rawString,
                rtfData: rtfData,
                createdAt: Date(),
                isPinned: false,
                sourceAppName: appName,
                sourceAppBundleID: bundleID,
                contentHash: contentHash
            )
            onItemCopied?(item, nil)
        }
    }

    private func extractFilePaths() -> [String]? {
        // Method A: readObjects for NSURL
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
            let paths = urls.filter { $0.isFileURL }.map { $0.path }
            if !paths.isEmpty {
                return paths
            }
        }

        // Method B: NSFilenamesPboardType
        if let filenames = pasteboard.propertyList(forType: .init("NSFilenamesPboardType")) as? [String], !filenames.isEmpty {
            return filenames
        }

        return nil
    }

    private func extractImageData() -> (Data, CGSize)? {
        // 1. Direct PNG data
        if let pngData = pasteboard.data(forType: .png), !pngData.isEmpty {
            if let image = NSImage(data: pngData) {
                return (pngData, image.size)
            }
        }

        // 2. TIFF conversion to PNG (Native macOS screenshot format)
        if let tiffData = pasteboard.data(forType: .tiff), !tiffData.isEmpty {
            if let imageRep = NSBitmapImageRep(data: tiffData),
               let pngData = imageRep.representation(using: .png, properties: [:]) {
                let size = CGSize(width: imageRep.pixelsWide, height: imageRep.pixelsHigh)
                return (pngData, size)
            }
        }

        // 3. NSImage from pasteboard objects
        if let image = NSImage(pasteboard: pasteboard), let tiffData = image.tiffRepresentation {
            if let imageRep = NSBitmapImageRep(data: tiffData),
               let pngData = imageRep.representation(using: .png, properties: [:]) {
                let size = CGSize(width: imageRep.pixelsWide, height: imageRep.pixelsHigh)
                return (pngData, size)
            }
        }

        return nil
    }

    private func isImageFilePath(_ path: String) -> Bool {
        let lower = path.lowercased()
        return lower.hasSuffix(".png") || lower.hasSuffix(".jpg") || lower.hasSuffix(".jpeg") ||
               lower.hasSuffix(".heic") || lower.hasSuffix(".webp") || lower.hasSuffix(".gif") ||
               lower.hasSuffix(".tiff") || lower.hasSuffix(".bmp")
    }

    private func detectContentType(for string: String) -> ItemContentType {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        // URL Check
        if trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://") {
            if let url = URL(string: trimmed), url.host != nil {
                return .url
            }
        }

        // Code heuristic check
        let codeIndicators = [
            "func ", "def ", "class ", "struct ", "enum ", "import ", "const ", "let ", "var ",
            "return ", "public ", "private ", "interface ", "package ", "namespace ",
            "=>", "->", "/*", "*/", "//", "{\n", "}\n", "console.log", "print("
        ]
        var score = 0
        for indicator in codeIndicators where string.contains(indicator) {
            score += 1
        }
        if score >= 2 || (string.contains("{") && string.contains("}") && string.contains(";")) {
            return .code
        }

        return .text
    }
}
